### ISSUE TITLE
Changing the default country displayed

### ISSUE THREAD

**Issue by wiki-me** [igorlogius/get-similarweb-info#1]
When i pop up a window it shows the country rank as that of the US (At least for sites like linkedin.com), I would like him to show it for my country (e.g. If i am living in spain it should show the rank in spain, like alexa rank seemed to do).

**Comment by igorlogius** [comment]
You are speaking about the "Country Rank", right? 
It looks to me that it displays the rank of the country where the site is supposedly hosted / located.

There is not much i can do about that, since I am only embedding their (mobile) site ... so people dont have to install their  nasty invasiv user tracking addon.   

You could of course ask the similarweb guys if they can add the  rank for the requesting IP (your supposed location) to their site. 

It they do, it should automagically  appear in the addon too.
